// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6F9WXTmBf1OyntucADVeZj8oV-_zleDg',
    appId: '1:36490115460:web:8bd798879f14aed4d0c5d1',
    messagingSenderId: '36490115460',
    projectId: 'mobile-7d484',
    authDomain: 'mobile-7d484.firebaseapp.com',
    storageBucket: 'mobile-7d484.appspot.com',
    measurementId: 'G-3NX5VXKH72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LHlTbZtAOn1u2pOBkebTaXY6YNeO57E',
    appId: '1:36490115460:android:68941e60cf797c18d0c5d1',
    messagingSenderId: '36490115460',
    projectId: 'mobile-7d484',
    storageBucket: 'mobile-7d484.appspot.com',
  );
}
